### ISSUE TITLE
unzureichendes user model

### ISSUE THREAD

**Issue by Haargeeel** [TomWieschalla/Masterprojekt-WS15-16-MMI-IoT#1]
Keyschema für Users bringt mir nicht viel.
Key sollte nicht "nur" die ID sein, da ich im Frontend beim Login nur den usernamen (oder email) bekomme. Man sollte also auch nach dem usernamen "queryen" können. Der sollte demnach auch einmalig sein.

**Comment by steven-maasch** [comment]
Können wir vollständig auf die Angabe einer E-Mail verzichten?

**Comment by Haargeeel** [comment]
Ohne E-Mail Service... Bin auch für einen einzigartigen usernamen
