### ISSUE TITLE
Bug beim initialisieren

### ISSUE THREAD

**Issue by TomWieschalla** [TomWieschalla/Masterprojekt-WS15-16-MMI-IoT#13]
Beim initialisieren hat der Nutzer keine Namen mehr 
Kein Sensor wird gespeichert
Kein Cluster wird gespeichert
Kein Gateway wird gespeichert

**Comment by steven-maasch** [comment]
Welchen User meinst du? admin?

```javascript
[
  {
    "username": "admin",
    "firstname": null,
    "lastname": null,
    "roles": [
      "ROLE_USER",
      "ROLE_ADMIN"
    ],
    "sensorList": []
  },
  {
    "username": "max",
    "firstname": "max",
    "lastname": "mustermann",
    "roles": [
      "ROLE_USER"
    ],
    "sensorList": [
      "1db25a79-d0c0-4f5b-b798-6902442bc513",
      "40c66d44-de57-49f7-b94e-4e9d21318b7b",
      "18030749-9a22-4c7b-b8ba-01380ab6f2f0"
    ]
  }
]
````

**Comment by TomWieschalla** [comment]
Bei mir hat er nur den Admin angezeigt ja Max musste ich mir ?ber Postman erstellen

Gru? Tom

Am 21.01.2016 um 21:45 schrieb Steven Maasch <notifications@github.com<mailto:notifications@github.com>>:


Welchen User meinst du? admin?

[
  {
    "username": "admin",
    "firstname": null,
    "lastname": null,
    "roles": [
      "ROLE_USER",
      "ROLE_ADMIN"
    ],
    "sensorList": []
  },
  {
    "username": "max",
    "firstname": "max",
    "lastname": "mustermann",
    "roles": [
      "ROLE_USER"
    ],
    "sensorList": [
      "1db25a79-d0c0-4f5b-b798-6902442bc513",
      "40c66d44-de57-49f7-b94e-4e9d21318b7b",
      "18030749-9a22-4c7b-b8ba-01380ab6f2f0"
    ]
  }
]

-

**Comment by steven-maasch** [comment]
Könne wir den Issue schließen? Problem/Fehler tritt bei mir nicht auf.

**Comment by Haargeeel** [comment]
Bei mir wird auch nichts initialisiert und es ist schon ein wenig nervig.

**Comment by TomWieschalla** [comment]
du musst die app.properties datei aktualisieren

**Comment by TomWieschalla** [comment]
# validate, drop-create, create-missing
db.init.table.mode=validate
db.init.dummy_data=true
