### ISSUE TITLE
print* mit logger ersetzen

### ISSUE THREAD

**Issue by steven-maasch** [TomWieschalla/Masterprojekt-WS15-16-MMI-IoT#7]
System.out.print Anweisungen durch äquivalente Logging Anweisungen ersetzen.

**Comment by TomWieschalla** [comment]
hab jetzt den slf4j logger genommen und alle ersetzt .. waren allerdings nur 3 oder so 

würde gerne den ERROR mal fixen:
ERROR StatusLogger No Log4j context configuration provided. This is very unusual.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

schon mal geschafft?

**Comment by TomWieschalla** [comment]
done
